vich_uploader:
  db_driver: orm
  storage: flysystem

  mappings:
    vote_reports:
        uri_prefix: '%env(AZURE_PUBLIC_URL)%/%env(AZURE_STORAGE_CONTAINER)%'
        upload_destination: vote_reports.storage
        namer: vich_uploader.namer_uniqid
    
    party_logos:
        uri_prefix: '%env(AZURE_PUBLIC_URL)%/%env(AZURE_STORAGE_CONTAINER)%'
        upload_destination: vote_reports.storage
        namer: vich_uploader.namer_uniqid
