<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251227194933 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bureau_de_vote (id UUID NOT NULL, nom VARCHAR(100) NOT NULL, code VARCHAR(20) NOT NULL, nombre_inscrits INT NOT NULL, centre_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1CE1240677153098 ON bureau_de_vote (code)');
        $this->addSql('CREATE INDEX IDX_1CE12406463CD7C3 ON bureau_de_vote (centre_id)');
        $this->addSql('CREATE TABLE centre_de_vote (id UUID NOT NULL, nom VARCHAR(150) NOT NULL, code VARCHAR(50) NOT NULL, adresse VARCHAR(255) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, circonscription_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_33DAA04677153098 ON centre_de_vote (code)');
        $this->addSql('CREATE INDEX IDX_33DAA046755DBAE ON centre_de_vote (circonscription_id)');
        $this->addSql('CREATE TABLE circonscription (id UUID NOT NULL, nom VARCHAR(100) NOT NULL, code VARCHAR(10) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FEDDA65A77153098 ON circonscription (code)');
        $this->addSql('CREATE TABLE parti (id UUID NOT NULL, nom VARCHAR(255) NOT NULL, sigle VARCHAR(50) NOT NULL, logo_url VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_94225E848776B952 ON parti (sigle)');
        $this->addSql('CREATE TABLE participation (id UUID NOT NULL, nombre_votants INT NOT NULL, heure_pointage TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, metadata_location JSON DEFAULT NULL, bureau_de_vote_id UUID NOT NULL, assesseur_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AB55E24F44298AD6 ON participation (bureau_de_vote_id)');
        $this->addSql('CREATE INDEX IDX_AB55E24F6A0AF12C ON participation (assesseur_id)');
        $this->addSql('CREATE TABLE resultat (id UUID NOT NULL, nombre_voix INT NOT NULL, pv_image_name VARCHAR(255) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_validated BOOLEAN NOT NULL, bureau_de_vote_id UUID NOT NULL, parti_id UUID NOT NULL, assesseur_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E7DB5DE244298AD6 ON resultat (bureau_de_vote_id)');
        $this->addSql('CREATE INDEX IDX_E7DB5DE2712547C6 ON resultat (parti_id)');
        $this->addSql('CREATE INDEX IDX_E7DB5DE26A0AF12C ON resultat (assesseur_id)');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, assigned_bureau_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D93D6494BF0DA40 ON "user" (assigned_bureau_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE bureau_de_vote ADD CONSTRAINT FK_1CE12406463CD7C3 FOREIGN KEY (centre_id) REFERENCES centre_de_vote (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE centre_de_vote ADD CONSTRAINT FK_33DAA046755DBAE FOREIGN KEY (circonscription_id) REFERENCES circonscription (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT FK_AB55E24F44298AD6 FOREIGN KEY (bureau_de_vote_id) REFERENCES bureau_de_vote (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT FK_AB55E24F6A0AF12C FOREIGN KEY (assesseur_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE resultat ADD CONSTRAINT FK_E7DB5DE244298AD6 FOREIGN KEY (bureau_de_vote_id) REFERENCES bureau_de_vote (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE resultat ADD CONSTRAINT FK_E7DB5DE2712547C6 FOREIGN KEY (parti_id) REFERENCES parti (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE resultat ADD CONSTRAINT FK_E7DB5DE26A0AF12C FOREIGN KEY (assesseur_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D6494BF0DA40 FOREIGN KEY (assigned_bureau_id) REFERENCES bureau_de_vote (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bureau_de_vote DROP CONSTRAINT FK_1CE12406463CD7C3');
        $this->addSql('ALTER TABLE centre_de_vote DROP CONSTRAINT FK_33DAA046755DBAE');
        $this->addSql('ALTER TABLE participation DROP CONSTRAINT FK_AB55E24F44298AD6');
        $this->addSql('ALTER TABLE participation DROP CONSTRAINT FK_AB55E24F6A0AF12C');
        $this->addSql('ALTER TABLE resultat DROP CONSTRAINT FK_E7DB5DE244298AD6');
        $this->addSql('ALTER TABLE resultat DROP CONSTRAINT FK_E7DB5DE2712547C6');
        $this->addSql('ALTER TABLE resultat DROP CONSTRAINT FK_E7DB5DE26A0AF12C');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D6494BF0DA40');
        $this->addSql('DROP TABLE bureau_de_vote');
        $this->addSql('DROP TABLE centre_de_vote');
        $this->addSql('DROP TABLE circonscription');
        $this->addSql('DROP TABLE parti');
        $this->addSql('DROP TABLE participation');
        $this->addSql('DROP TABLE resultat');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
